version: '3'
services:
  eureka-service:
    image: com.percolata/eureka-service:0.0.2-SNAPSHOT
    restart: always
    ports:
      - "6001:6001"
    volumes:
      - /home/deployer/log_staffum:/tmp
  store-service:
    image: com.percolata/store-service:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "6301:6301"
    links:
      - eureka-service
    volumes:
      - /home/deployer/log_staffum:/tmp

