version: '3'
services:
  eureka-service:
    image: com.relengxing/eureka-service:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "6001:6001"
    volumes:
      - /home/deployer/deploy_log:/tmp
  client-service:
    image: com.percolata/store-service:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "7001:7001"
    links:
      - eureka-service
    volumes:
      - /home/deployer/deploy_log:/tmp

