version: '3'
services:
  eureka-service:
    image: com.relengxing/eureka:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "7000:7000"
    volumes:
      - /home/deployer/deploy_log:/tmp
  client-service:
    image: com.relengxing/client:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "7100:7100"
    links:
      - eureka-service
    volumes:
      - /home/deployer/deploy_log:/tmp

