app:
  environment: default

server:
    port: 7100
logging:
  file: /tmp/client-log.log
  level: info
spring:
  application:
    name: client
eureka:
  client:
    service-url:
      defaultZone: http://client-service:7000/eureka/
